spring:
  application:
    name: GOVIYA-BIDDING-SERVICE
  boot:
    admin:
      client:
        url: http://localhost:9188
        enabled: true
        auto-registration: true
  profiles:
    active: local

server:
  port: 9188
  servlet:
    context-path: /api/goviya-bidding-core

swagger:
  server-url: http://52.118.205.242:9188

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none
